[SECD] Bumping OpenTitan
pulp-platform/astral pull request #3
Opened 2024-03-13 16:37 UTC by maicolciani

Bumping OpenTitan to a ligher version: 
- 32KB of SRAM and 64KB of emulated flash.
- iDMA and TCDM integration, dedicated to cryptographic accelrators

2024-03-13 22:09 UTC, yvantor requested changes
Thanks for the PR! I left some comments.

2024-03-13 22:09 UTC, yvantor commented on hw/carfield_pkg.sv
> +  if (island_cfg.secured.enable)      begin ret++; end
Could we directly increase by two sice we already know that there will be two master ports provided. Also, please try avoiding adding spaces if not needed.
```suggestion
  if (island_cfg.safed.enable  ) begin ret++; end
  if (island_cfg.spatz.enable  ) begin ret++; end
  if (island_cfg.pulp.enable   ) begin ret++; end
  if (island_cfg.secured.enable) begin ret+=2; end
```

2024-03-13 22:09 UTC, yvantor commented on hw/carfield_pkg.sv
> +  IntClusterMstIdx         = CarfieldMstIdx.pulp
```suggestion
  SafetyIslandMstIdx       = CarfieldMstIdx.safed,
  SecurityIslandTlulMstIdx = CarfieldMstIdx.secured,
  SecurityIslandiDMAMstIdx = CarfieldMstIdx.secured_idma,
  FPClusterMstIdx          = CarfieldMstIdx.spatz,
  IntClusterMstIdx         = CarfieldMstIdx.pulp
```

2024-03-19 22:37 UTC, maicolciani commented on hw/carfield_pkg.sv
> +  islands_properties_t secured_idma;
actually this structure is also used in the definition of the [Carfield mmap config](https://github.com/pulp-platform/astral/blob/f3b934ac54fe0897c9e5bf3b43f7f63d09601be2/hw/carfield_pkg.sv#L333), without secured secured_idma entries here we got errors.

2024-03-19 22:38 UTC, maicolciani commented on hw/carfield.sv
> +    .axi_isolated_o   ( { unused, master_isolated_rsp[SecurityIslandTlulMstIdx] } ),
fixed

2024-03-19 22:38 UTC, maicolciani commented on hw/carfield.sv
> +    .HartIdOffs            ( 4           ),
fixed

2024-03-19 22:38 UTC, maicolciani commented on hw/carfield.sv
> +         master_isolated_rsp[SecurityIslandTlulMstIdx];
fixed

2024-03-19 22:40 UTC, maicolciani commented
Almost fixed all the comments. Still I get a test failing the CI, the CVA6 test with bootmode=3. I am debugging the issue.

2024-03-19 22:40 UTC, maicolciani commented on hw/carfield_pkg.sv
> +  IntClusterMstIdx         = CarfieldMstIdx.pulp
fixed

2024-03-19 22:40 UTC, maicolciani commented on hw/carfield_pkg.sv
> +  if (island_cfg.secured.enable)      begin ret++; end
fixed

2024-03-21 10:31 UTC, yvantor commented
> Almost fixed all the comments. Still I get a test failing the CI, the CVA6 test with bootmode=3. I am debugging the issue.

That one should be solved, it is probably just the server that got stuck due to many jobs running running in parallel.

2024-03-21 13:22 UTC, maicolciani commented on hw/carfield_pkg.sv
> +  islands_properties_t secured_idma;
removed as discussed today in the meeting, indeed not needed

2024-03-21 13:23 UTC, maicolciani commented
> > Almost fixed all the comments. Still I get a test failing the CI, the CVA6 test with bootmode=3. I am debugging the issue.
> 
> That one should be solved, it is probably just the server that got stuck due to many jobs running running in parallel.

I removed that parameters from islands_cfg_t as disucssed, indeed not needed. When CI finishes I think we can merge

2024-03-26 09:48 UTC, yvantor approved these changes
LGTM

2024-03-26 09:50 UTC, merged